language: node_js
node_js:
  - '8'
sudo: required
dist: trusty
addons:
  chrome: stable
before_script:
  - 'sudo chown root /opt/google/chrome/chrome-sandbox'
  - 'sudo chmod 4755 /opt/google/chrome/chrome-sandbox'

cache:
  directories:
    - '$HOME/.npm'
useYarn: true
env:
  global:
    - JOBS=1
matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
  - npm config set spin false
  - npm --version
script:
  - npm run lint:js
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup

stages:
  - basic test
  - additional tests
jobs:
  fail_fast: true
  include:
    - stage: basic test
      env: EMBER_TRY_SCENARIO=ember-release
    - stage: additional tests
      env: EMBER_TRY_SCENARIO=ember-lts-2.12
    - env: EMBER_TRY_SCENARIO=ember-lts-2.16
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary

after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
